"""empty message

Revision ID: 2bae1737567c
Revises: d96d44874ae7
Create Date: 2018-02-17 16:59:46.753379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bae1737567c'
down_revision = 'd96d44874ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('accounts', sa.Column('secondary_address', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('accounts', sa.Column('street_address', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('zip_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'zip_code')
    op.drop_column('accounts', 'street_address')
    op.drop_column('accounts', 'state')
    op.drop_column('accounts', 'secondary_address')
    op.drop_column('accounts', 'city')
    # ### end Alembic commands ###
