"""empty message

Revision ID: 5f40679c0d17
Revises: c8c5746ed9fd
Create Date: 2018-03-10 15:01:06.963730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f40679c0d17'
down_revision = 'c8c5746ed9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('converted_date', sa.Date(), nullable=True))
    op.add_column('subscriptions', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('subscriptions', sa.Column('expired_date', sa.Date(), nullable=True))
    op.add_column('subscriptions', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('subscriptions', sa.Column('type', sa.Integer(), nullable=False))
    op.drop_column('subscriptions', 'trial_start_date')
    op.drop_column('subscriptions', 'subscription_end_date')
    op.drop_column('subscriptions', 'trial_end_date')
    op.drop_column('subscriptions', 'subscription_start_date')
    op.drop_column('subscriptions', 'trial_expired_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('trial_expired_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('subscription_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('trial_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('subscription_end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('trial_start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'type')
    op.drop_column('subscriptions', 'start_date')
    op.drop_column('subscriptions', 'expired_date')
    op.drop_column('subscriptions', 'end_date')
    op.drop_column('subscriptions', 'converted_date')
    # ### end Alembic commands ###
