"""empty message

Revision ID: 63e740b54986
Revises: 896ef6c3893c
Create Date: 2018-02-24 13:52:29.524288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e740b54986'
down_revision = '896ef6c3893c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('accounts', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_updated')
    op.drop_column('users', 'created_at')
    op.drop_column('accounts', 'last_updated')
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
