"""empty message

Revision ID: 92bb4e2c855b
Revises: f357a16e828b
Create Date: 2018-03-24 10:44:19.762928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bb4e2c855b'
down_revision = 'f357a16e828b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('default_subscription_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'default_subscription_price')
    # ### end Alembic commands ###
