"""empty message

Revision ID: c8c5746ed9fd
Revises: 6e2e33c416a5
Create Date: 2018-03-10 13:17:13.054206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c5746ed9fd'
down_revision = '6e2e33c416a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('text_alerts', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('voice_alerts', sa.Boolean(), nullable=True))
    op.add_column('subscriptions', sa.Column('voice_alerts_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'voice_alerts_phone')
    op.drop_column('subscriptions', 'voice_alerts')
    op.drop_column('subscriptions', 'text_alerts')
    # ### end Alembic commands ###
