"""empty message

Revision ID: d19cd3c5bd71
Revises: 92bb4e2c855b
Create Date: 2018-05-29 13:46:23.524223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19cd3c5bd71'
down_revision = '92bb4e2c855b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'converted_date')
    op.drop_column('subscriptions', 'conversion_emails_sent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('conversion_emails_sent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('converted_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
