"""empty message

Revision ID: f249d6536e0d
Revises: a93b446341f0
Create Date: 2018-03-10 16:11:59.043411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f249d6536e0d'
down_revision = 'a93b446341f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status2', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('type2', sa.String(), nullable=False))
    op.drop_column('subscriptions', 'status')
    op.drop_column('subscriptions', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'type2')
    op.drop_column('subscriptions', 'status2')
    # ### end Alembic commands ###
