"""empty message

Revision ID: f357a16e828b
Revises: f249d6536e0d
Create Date: 2018-03-10 16:12:11.022964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f357a16e828b'
down_revision = 'f249d6536e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('subscriptions', 'type2')
    op.drop_column('subscriptions', 'wtf')
    op.drop_column('subscriptions', 'status2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status2', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('wtf', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('type2', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'type')
    op.drop_column('subscriptions', 'status')
    # ### end Alembic commands ###
